### ISSUE TITLE
Sources with Alpha

### ISSUE THREAD

**Issue by stevespaw** [MindStudioOfficial/ndiscopes#1]
This looks great so far as I play with it!
The only issue I have found so far is corrupt display of NDI with alpha.
I have tried several sources including the NDI test pattern - creating a "custom" with a .png file.
Let me know if you have any questions.

Thanks again,
Steve
 I am on the .03 beta BTW

**Comment by MindStudioOfficial** [comment]
Alright, got it, working on it now. I thought I tested it with alpha... turns out i didn't :D

**Comment by MindStudioOfficial** [comment]
Found the issue. The frame viewer assumed premultiplied alpha but the NDI frame isn't premultiplied so I fixed it by adding a color transformation matrix that makes the alpha channel only depend on the alpha channel... I know.. sounds stupid :D

Fix will be in the next release

**Comment by stevespaw** [comment]
Great, I will watch for updates! Thanks
