### ISSUE TITLE
raw metadata aspect ratio format

### ISSUE THREAD

**Issue by GralfR** [MindStudioOfficial/ndiscopes#10]
**Is your feature request related to a problem? Please describe.**
in addition to #5: would be great to have the format shown also in more typical format if it matches to common ratios like 4:3, 16:9 etc. It's hard to imagine all common ratios from a decimal number.

**Describe the solution you'd like**
e.g.: `Aspect Ratio 1.7778 = 16:9`

**Describe alternatives you've considered**
Using calculator to calculate 16:9 and compare to the shown Aspect Ratio is slow and annoying.

**Additional context**
#5

**Comment by MindStudioOfficial** [comment]
> Using calculator to calculate 16:9 and compare to the shown Aspect Ratio is slow and annoying.

I do agree :D

**Comment by MindStudioOfficial** [comment]
![grafik](https://user-images.githubusercontent.com/62838401/196899830-d61774cb-7167-4c77-8651-2c44c5385960.png)

How about that?

**Comment by MindStudioOfficial** [comment]
Implemented in v0.7.3-beta
