### ISSUE TITLE
Error loading Audio Device

### ISSUE THREAD

**Issue by afburgos** [MindStudioOfficial/ndiscopes#11]
**Describe the bug**
opening the program, says "error loading audio devices Range error (index) invalid value. Only valid valuie is 0 : 1

**To Reproduce**

**Expected behavior**

**Screenshots**

**Hardware/Software**
- Version of Windows
- GPU Type/Manufacturer

**Additional context**

**Comment by MindStudioOfficial** [comment]
This Issue is currently beeing tracked as #6. Thus I am marking this as a duplicate.
