### ISSUE TITLE
Audio Meters

### ISSUE THREAD

**Issue by stevespaw** [MindStudioOfficial/ndiscopes#2]
Any Chance for Audio Meters?
This would a nice next to a phabrix :-)

**Comment by MindStudioOfficial** [comment]
Audio is not really the priority of this Project but I might add them in the future.

**Comment by stevespaw** [comment]
Watching this space for your updates. Very nice work, I am enjoying it, and look forward to deploying it with our team. Thanks!

**Comment by MindStudioOfficial** [comment]
@stevespaw actually worked all day on it. Made the first version!

It is not in a release yet but will be in the next.

![grafik](https://user-images.githubusercontent.com/62838401/165194160-8baad087-cc96-4d3d-9a8c-928d253101a8.png)
- Loudness is displayed in dBu. 
- White line is at 0dBu. 
- Levels in picture are 4 channels at +18 dBu
- Max is +24 dBu

If you have any more suggestions or wishes feel free to comment on here!

**Comment by stevespaw** [comment]
Wow great work! I can't believe you got here this quickly. I look forward to having this as a part of a QA station.

**Comment by MindStudioOfficial** [comment]
@stevespaw I programmed it to show all incoming channels. Theoretically there are no limits to the amount of channels in an NDI signal. The number of meter-bars changes based on the number of channels. So if you give it an NDI sginal with 16 channels it should show all of them but the bars might be very thin to the point where you might not be able to differentiate different channels.

I am going to test this further with the limited hardware I have.

**Comment by stevespaw** [comment]
We may have 16 channels at the most for embedding intercom/IFB feeds. This is also the limit for SDI. The NDI5 VST plugin lets you add 16 channels pretty easily.
Thanks.

Thanks,
Steve



[Description: Steve Cursive]
Steve Spaw
[Description: Shadow50 trans]      ***@***.******@***.***?subject=Video%20System>
www.shadow-technologies.com<http://www.shadow-technologies.com>

**Comment by MindStudioOfficial** [comment]
@stevespaw just uploaded a new release. Feel free to test the new feature and send back any bugs you find or changes you want.

**Comment by stevespaw** [comment]
Ok there is a famous kids book "If you give a mouse a cookie". You had to know the next ask. Can you route the Audio to an output device? Like Studio Monitor? :-) Otherwise it looks nice at first glance I will spend more time tonight.

**Comment by MindStudioOfficial** [comment]
@stevespaw sadly not right now. The frameworks ONLY audio plugin that supports windows is missing a critical feature as of now. I would have to write my own audio plugin to actually play audio and that would take some time.

**Comment by stevespaw** [comment]
![image](https://user-images.githubusercontent.com/11045430/165639270-7f3006c7-776f-4d5c-93ad-1cf378ceb1da.png)
Here is 16 Channels on a 4K monitor- Nice

**Comment by stevespaw** [comment]
Kinda small, Could we replace one of the 3 "scopes" with this Meter Bridge? In Settings?

**Comment by MindStudioOfficial** [comment]
@stevespaw I wouldn't replace a scope but I could make it bigger or resizable.

**Comment by MindStudioOfficial** [comment]
@stevespaw I managed to implement a windows audio library to playback sound. After a Week of tinkering I got it to work. I have audio playback running now but it needs to be tested a lot. I will make a release soon that will have audio playback.

**Comment by stevespaw** [comment]
Wow this is great, can't wait to see (hear) it!
