### ISSUE TITLE
crashing on startup

### ISSUE THREAD

**Issue by joniose** [MindStudioOfficial/ndiscopes#7]
I can't open the NDI Scope App. When I start it, the Task-Manager shows the App for a few seconds. Than it crashes - without opening a window.
I have tested 6.2, 7.0 & 7.1

**Hardware/Software**
- Laptop: Gigabyte, AERO 15-X9
- Version of Windows: 22H2 Build 22651.525 --> New Install
- CPU: i7-8750H
- GPU: Nvidia RTX 2070 Max-Q

**Comment by MindStudioOfficial** [comment]
What GPU driver version are you on?

**Comment by joniose** [comment]
Studio Driver 517.40

**Comment by MindStudioOfficial** [comment]
Does it work with the Gaming drivers?

Interestingly I am using an AERO aswell to test the app. It is an older model but it works fine on mine. The only difference apart from specific hardware is the Studio vs. Gaming drivers.

EDIT: The Studio driver should not really make a difference since it appears to be just a more stable version of the more frequently updated game ready drivers.

**Comment by joniose** [comment]
ok thank you. I check the Game-Ready drivers.

Have you deinstalled Nahimic - because it made some troubles for other Software some time ago

**Comment by MindStudioOfficial** [comment]
This type of crash is rather unusual for this kind of application. To me this looks like an antivirus application is blocking NDIScopes from running and killing the process. Because even if you have an incompatible GPU the app should still open and display an error message accordingly.

**Comment by joniose** [comment]
i have reinstalled Windows, and not installed any anti-virus software.

**Comment by MindStudioOfficial** [comment]
> Have you deinstalled Nahimic - because it made some troubles for other Software some time ago


I don't think I have uninstalled it. I remember reading something like nahimic on the laptop somewhere.

**Comment by joniose** [comment]
With Game-ready Driver i have the same Problem:

after 4s in "Backgroud-tasks" it is away

**Comment by joniose** [comment]
Do I need NDI installed? Because I have installed Version 5.5.1.0

**Comment by MindStudioOfficial** [comment]
> Do I need NDI installed? Because I have installed Version 5.5.1.0

No you don't need it unless you want to create and manage sources locally. The NDI runtime is included in the app.

NDIScopes uses NDI 5.5.1.0.

**Comment by MindStudioOfficial** [comment]
Are you unzipping the release file correctly? And where are you putting the files? Maybe the .exe doesn't have the necessary permissions to read all the necessary files because you put it in a location where it needs administrator rights to do so.

**Comment by joniose** [comment]
I have used the windows explorer to unzip.

File location = User/Downloads

I've tried opening the file with administrator rights. But that didn't changed anything.

**Comment by MindStudioOfficial** [comment]
Then I am sadly out of Ideas :(

**Comment by joniose** [comment]
thank you very much for your help!

Hopefully I will find the problem :)

**Comment by MindStudioOfficial** [comment]
@joniose and please let me know what the problem was once you found it and how you solved it :D

Some more ideas I had were: Windows defender, Nvidia config (maybe some fighting between iGPU of the CPU and the NVIDIA GPU)

... I just realised that you are using windows 11 instead of 10. I haven't tested windows 11 yet...

**Comment by MindStudioOfficial** [comment]
I researched more and found that Windows 11 still causes problems with the UI framework I am using to make the software. Maybe it works on Windows 10.

**Comment by joniose** [comment]
Windows 11 could be the Problem ...

i have tested compatibility mode, but that didn't worked :P

**Comment by MindStudioOfficial** [comment]
I sadly don't have access to a PC with Windows 11 right now, so I can't test it for now.

**Comment by joniose** [comment]
i have tested it on a win11 machine. but mine is on 22H2

**Comment by MindStudioOfficial** [comment]
um... I currently can't start the app on my PC. I am on 22H2 too 😲

**Comment by MindStudioOfficial** [comment]
Nevermind, I thought 22H2 was Windows 11 but it's on Windows 10. I am on 22H2 too.

I am currently making the release v0.7.2-beta which is built on 22H2 with an updated version of the framework. Maybe this version works for you.

**Comment by joniose** [comment]
> i have tested it on a win11 machine. but mine is on 22H2

I meant: I tested it on another PC running on original Win 11. There it worked :)

the aero laptop is on Win11 22H2, the september 22 update (because I reinstalled windows ;)
On this laptop the software crashes

**Comment by joniose** [comment]
> I am currently making the release v0.7.2-beta which is built on 22H2 with an updated version of the framework. Maybe this version works for you.

sounds great :)
thank you

I will test it as soon you release the update :)

**Comment by MindStudioOfficial** [comment]
I have released the update: https://github.com/MindStudioOfficial/ndiscopes/releases/tag/v0.7.2-beta
Let me know if it works :D

The update already fixed someone elses startup failure so maybe it will fix yours too :D
https://github.com/MindStudioOfficial/ndiscopes/issues/4#issuecomment-1285055109

**Comment by joniose** [comment]
it works 💯 

thank you

**Comment by MindStudioOfficial** [comment]
Then it was probably an issue with the UI framework that has been fixed in the meantime.

Glad that it works! :D
