### ISSUE TITLE
raw Metadata copy to clipboard

### ISSUE THREAD

**Issue by GralfR** [MindStudioOfficial/ndiscopes#9]
**Describe the bug**
In 0.7.2beta one can select several lines in the metadata, but only the last one is copied to clipboard

**To Reproduce**
1. enable Metadata
2. highlight any of the shown items (e.g. Sourcename)
3. highlight another item (e.g. Source-IP)
4. both items are shown as selected/highlighted

**Expected behavior**
A Ctrl-C should copy the highlighted text into clipboard. Because several items are highlighted, all highlighted text is expected to be copied - altough this is a bit strange, because you can't select the headlines/first column. The normal expected behaviour would be, that highlighting/selecting any item would remove the selection on other items.

**Hardware/Software**
- Win10 LTSB 1607 x64
- NVIDIA GTX1080 Ti

**Additional context**
I didn't expect to be able to copy all metadata in one step. I even did not expect to be able to select several items together. So, the main problem is: selecting one item does not deselect others.

**Comment by MindStudioOfficial** [comment]
This is an Issue with the text not unhighlighting when clicking somewhere else. This is not intended.

**Comment by MindStudioOfficial** [comment]
The fix will be released in v0.8.0-beta
